/**
 * LoRA 학습 데이터 — 한국 건축 200개 지점
 * 서울 25개 구 + 경기도 주요 도시 전체 커버
 * 6개 카테고리: villa(70) / apartment(40) / commercial(35) / luxury(25) / officetel(15) / mixed(15)
 */
export interface TrainingPoint {
  lat: number; lng: number
  category: 'villa' | 'apartment' | 'commercial' | 'luxury' | 'officetel' | 'mixed'
  district: string; caption: string; heading?: number
}
export const TRAINING_POINTS: TrainingPoint[] = [
// ━━━ 빌라/다세대 (70) ━━━
{lat:37.5172,lng:127.0473,category:'villa',district:'강남구 논현동',caption:'Korean multi-family villa, 4-story walk-up, beige exterior tiles, pilotis ground floor parking, balcony with laundry drying racks, external staircase, flat roof with water tanks, narrow residential alley in Gangnam Seoul'},
{lat:37.5145,lng:127.0412,category:'villa',district:'강남구 논현동',caption:'Korean villa apartment, 5-story residential, exposed concrete and tile facade, metal railing balconies, rooftop equipment visible, parked cars at street level'},
{lat:37.5089,lng:127.0632,category:'villa',district:'강남구 삼성동',caption:'Modern Korean villa, 4-story multi-unit housing, clean white facade with gray accents, pilotis parking underneath, air conditioning outdoor units on facade'},
{lat:37.5198,lng:127.0389,category:'villa',district:'강남구 역삼동',caption:'Yeoksam-dong Korean villa, 5-story narrow building, brown brick lower floors, painted upper floors, rooftop solar water heater, urban residential area'},
{lat:37.4923,lng:127.0151,category:'villa',district:'서초구 방배동',caption:'Bangbae-dong Korean villa, 4-story multi-family, cream colored exterior, flower pots on balcony, small front garden, quiet residential street with mature trees'},
{lat:37.4856,lng:127.0073,category:'villa',district:'서초구 서초동',caption:'Seocho villa, 3-story renovated residential, modern gray paint, glass balcony railings, underground parking entrance, well-maintained landscaping'},
{lat:37.5662,lng:126.9247,category:'villa',district:'마포구 연남동',caption:'Yeonnam-dong Korean villa, 3-story walk-up, red brick exterior, old-style external staircase, narrow alley, mature trees, quiet residential near Hongdae'},
{lat:37.5493,lng:126.9134,category:'villa',district:'마포구 합정동',caption:'Hapjeong Korean multi-family, 4-story villa, renovated facade with modern tiles, rooftop terrace, street-level parking, mixed residential-commercial'},
{lat:37.5584,lng:126.9265,category:'villa',district:'마포구 연남동',caption:'Korean villa with rooftop garden, 4-story residential, warm-toned exterior paint, balcony with plants, external metal staircase, typical Seoul residential block'},
{lat:37.5539,lng:126.9193,category:'villa',district:'마포구 서교동',caption:'Seogyo-dong villa near Hongdae, 4-story aging building, exposed pipes, colorful door, narrow side street, mixed use ground floor, student neighborhood'},
{lat:37.5894,lng:127.0167,category:'villa',district:'성북구 정릉동',caption:'Korean hillside villa, 3-story multi-family on sloped terrain, retaining wall at base, exposed pipes, narrow uphill road, dense residential'},
{lat:37.6102,lng:127.0234,category:'villa',district:'강북구 수유동',caption:'Suyu-dong Korean villa, 4-story walk-up, pink painted exterior, metal window frames, steep alley with handrails, northern Seoul hillside housing'},
{lat:37.5978,lng:127.0089,category:'villa',district:'성북구 길음동',caption:'Gireum-dong villa, 5-story narrow building, brown tiles, pilotis parking, laundry on balcony, convenience store on ground floor'},
{lat:37.6543,lng:127.0557,category:'villa',district:'노원구 상계동',caption:'Korean suburban villa, 4-story walk-up near apartment complex, beige tile exterior, communal parking area, wide sidewalk, satellite dishes on roof'},
{lat:37.6487,lng:127.0312,category:'villa',district:'노원구 월계동',caption:'Wolgye-dong villa, 3-story residential, simple rectangular design, vinyl windows, shared parking lot, near elementary school'},
{lat:37.6689,lng:127.0445,category:'villa',district:'도봉구 쌍문동',caption:'Ssangmun-dong Korean villa, 4-story aging multi-family, exposed concrete repairs, narrow alley access, dense hillside neighborhood, mountain backdrop'},
{lat:37.4784,lng:126.9516,category:'villa',district:'관악구 신림동',caption:'Korean student-area villa near university, 5-story narrow building, many AC units on facade, convenience store at ground floor, steep hill road'},
{lat:37.4723,lng:126.9412,category:'villa',district:'관악구 봉천동',caption:'Bongcheon-dong villa, 4-story densely packed multi-family, shared wall construction, narrow passage between buildings, rooftop water tanks'},
{lat:37.5013,lng:126.9389,category:'villa',district:'동작구 사당동',caption:'Sadang-dong Korean villa, 4-story residential, white and gray exterior, metal gate entrance, motorcycle parking, urban residential street'},
{lat:37.4956,lng:126.9523,category:'villa',district:'동작구 상도동',caption:'Sangdo-dong villa, 3-story hillside multi-family, retaining wall, steep stairway entrance, rooftop clothesline, older Korean residential'},
{lat:37.5048,lng:127.1167,category:'villa',district:'송파구 가락동',caption:'Korean villa in Songpa, 4-story, brown brick exterior, organized parking lot, well-maintained landscaping, suburban feel within Seoul'},
{lat:37.5301,lng:127.1237,category:'villa',district:'강동구 명일동',caption:'Gangdong villa, 3-story residential, simple rectangular design, exposed concrete base, vinyl windows, typical Korean suburban residential'},
{lat:37.5178,lng:127.1089,category:'villa',district:'송파구 문정동',caption:'Munjeong-dong villa, 4-story newly built, modern design, stone-finish lower wall, glass balconies, structured parking'},
{lat:37.6019,lng:126.9292,category:'villa',district:'은평구 응암동',caption:'Korean villa in older neighborhood, 3-story walk-up, aging facade with partial renovation, external gas pipes visible'},
{lat:37.5791,lng:126.9368,category:'villa',district:'서대문구 연희동',caption:'Yeonhui-dong Korean villa, 4-story upscale multi-family, stone base wall, quality window frames, private garden, quiet wealthy residential'},
{lat:37.6134,lng:126.9167,category:'villa',district:'은평구 녹번동',caption:'Nokbeon-dong villa, 5-story narrow building, beige paint peeling, metal external staircase, rooftop antenna array, aging Seoul villa'},
{lat:37.5234,lng:126.8923,category:'villa',district:'영등포구 당산동',caption:'Dangsan-dong Korean villa, 4-story residential near subway, renovated white exterior, convenience store at ground level, bicycle parking'},
{lat:37.4956,lng:126.8567,category:'villa',district:'구로구 구로동',caption:'Guro-dong Korean villa, 3-story multi-family, industrial neighborhood, simple block design, shared parking, factory buildings nearby'},
{lat:37.5078,lng:126.8734,category:'villa',district:'구로구 신도림동',caption:'Sindorim villa, 4-story walk-up, mixed residential-industrial, older construction, external pipes, convenience shops at street level'},
{lat:37.5412,lng:127.0834,category:'villa',district:'광진구 자양동',caption:'Jayang-dong Korean villa, 4-story near Konkuk University, restaurants at ground floor, student housing above, neon signs'},
{lat:37.5534,lng:127.0589,category:'villa',district:'성동구 행당동',caption:'Haengdang-dong villa, 3-story older residential, green painted exterior, traditional Korean gate, narrow alley, aging residential block'},
{lat:37.5267,lng:126.8678,category:'villa',district:'양천구 목동',caption:'Mokdong villa, 4-story residential near apartment complexes, clean facade, organized parking, wide street, planned residential area'},
{lat:37.5512,lng:126.8434,category:'villa',district:'강서구 화곡동',caption:'Hwagok-dong Korean villa, 5-story narrow, pilotis parking, colorful awnings, residential street with many villas, western Seoul suburb'},
{lat:37.5967,lng:127.0756,category:'villa',district:'중랑구 면목동',caption:'Myeonmok-dong villa, 4-story aging multi-family, exposed brick wall, metal gate, steep hill, dense packed buildings'},
{lat:37.5745,lng:127.0412,category:'villa',district:'동대문구 전농동',caption:'Jeonnong-dong Korean villa, 3-story walk-up, yellow brick exterior, balcony with potted plants, quiet residential street near university'},
{lat:37.4567,lng:126.8989,category:'villa',district:'금천구 시흥동',caption:'Siheung-dong villa, 4-story industrial area residential, simple gray exterior, metal windows, small parking area, working class housing'},
{lat:37.5312,lng:126.9723,category:'villa',district:'용산구 효창동',caption:'Hyochang-dong Korean villa, 3-story multi-family, traditional neighborhood, aging brown tiles, small front garden, narrow alley near park'},
{lat:37.5823,lng:126.9989,category:'villa',district:'종로구 혜화동',caption:'Hyehwa-dong villa near Daehangno, 4-story residential, older construction, cultural district atmosphere, university students, small cafes nearby'},
{lat:37.3943,lng:127.1115,category:'villa',district:'성남시 수정구',caption:'Korean villa in Seongnam, 4-story multi-family, exposed brick, pilotis parking, laundry hanging on balcony, satellite city residential'},
{lat:37.6584,lng:127.0768,category:'villa',district:'의정부시',caption:'Korean suburban villa in Uijeongbu, 5-story walk-up, light pink exterior, commercial sign at ground floor, mixed residential'},
{lat:37.3219,lng:126.8312,category:'villa',district:'안산시 단원구',caption:'Industrial city Korean villa, 4-story, utilitarian design, vinyl siding, shared parking, working-class residential area'},
{lat:37.7517,lng:127.0477,category:'villa',district:'양주시',caption:'New construction Korean villa, 4-story modern design, clean facade, structured parking, new residential development in Gyeonggi Province'},
{lat:37.2756,lng:127.0094,category:'villa',district:'수원시 팔달구',caption:'Suwon Korean villa near Hwaseong Fortress, 4-story residential, traditional market nearby, mixed old-new architecture'},
{lat:37.4512,lng:126.7234,category:'villa',district:'부천시 원미구',caption:'Bucheon Korean villa, 5-story narrow building, aging pink exterior, many AC units, dense residential block, industrial city housing'},
{lat:37.3412,lng:126.9834,category:'villa',district:'과천시',caption:'Gwacheon villa, 3-story low-rise residential, government city, well-maintained, organized parking, clean streets, mountain views'},
{lat:37.7389,lng:127.0345,category:'villa',district:'동두천시',caption:'Dongducheon Korean villa, 4-story, military town character, simple construction, wide streets, northern Gyeonggi suburban residential'},
{lat:37.3156,lng:127.0789,category:'villa',district:'용인시 수지구',caption:'Suji villa, newly built 4-story, modern Korean suburban design, stone accent wall, private parking garage, new town development'},
{lat:37.4289,lng:126.9912,category:'villa',district:'안양시 만안구',caption:'Anyang Korean villa, 4-story walk-up, hillside location, retaining wall, external staircase with awning, dense residential near subway'},
{lat:37.5012,lng:126.7678,category:'villa',district:'인천시 부평구',caption:'Incheon Bupyeong villa, 5-story residential, industrial city housing, gray concrete exterior, narrow alleys, dense urban area'},
{lat:37.4134,lng:127.2567,category:'villa',district:'이천시',caption:'Icheon Korean villa, 3-story suburban residential, agricultural town, spacious lot, private garden, rural-urban transition zone'},
{lat:37.5934,lng:127.1456,category:'villa',district:'구리시',caption:'Guri Korean villa, 4-story, riverside city, clean modern renovation, organized parking, walking path nearby, suburban Seoul dormitory town'},
{lat:37.6534,lng:126.8345,category:'villa',district:'고양시 덕양구',caption:'Goyang villa, 4-story near new town, mixed old and new buildings, wide boulevard, Gyeonggi western suburban character'},
{lat:37.3756,lng:126.9567,category:'villa',district:'군포시',caption:'Gunpo Korean villa, 3-story compact residential, satellite city, organized neighborhood, small playground nearby, commuter town'},
{lat:37.4845,lng:126.9012,category:'villa',district:'안양시 동안구',caption:'Dongan-gu villa, 4-story modern design, clean white exterior, structured pilotis, near Pyeongchon new town'},
{lat:37.2389,lng:127.0823,category:'villa',district:'오산시',caption:'Osan Korean villa, 4-story suburban residential, military base nearby, wide streets, Korean small city residential character'},
{lat:37.3589,lng:127.1234,category:'villa',district:'광주시 경기',caption:'Gwangju-si Gyeonggi villa, 3-story rural-suburban transition, spacious yards, new construction mixed with older buildings'},
{lat:37.5623,lng:126.9834,category:'villa',district:'중구 신당동',caption:'Sindang-dong Seoul villa, 4-story inner city residential, aging but maintained, traditional market nearby, commercial ground floor'},
{lat:37.5456,lng:127.0156,category:'villa',district:'성동구 옥수동',caption:'Oksu-dong hillside villa, 3-story on steep slope, Namsan view, retaining walls, external stairs, traditional Seoul residential pocket'},
{lat:37.5734,lng:126.9567,category:'villa',district:'서대문구 홍은동',caption:'Hongeun-dong villa, 4-story walk-up, mountain foot location, aging exterior, steep narrow road, traditional Korean residential alley'},
{lat:37.6245,lng:127.0678,category:'villa',district:'중랑구 상봉동',caption:'Sangbong-dong villa, 5-story near subway, commercial ground floor, residential above, busy intersection, transit-area housing'},
{lat:37.4734,lng:127.0389,category:'villa',district:'서초구 양재동',caption:'Yangjae-dong villa, 4-story near expressway, modern renovation, soundproof windows, organized parking, suburban Seoul'},
{lat:37.5623,lng:127.0389,category:'villa',district:'성동구 금호동',caption:'Geumho-dong hillside villa, 3-story on steep terrain, stairway access, panoramic city view from rooftop, aging residential with character'},
{lat:37.5389,lng:126.8289,category:'villa',district:'강서구 등촌동',caption:'Deungchon-dong villa, 4-story near Gimpo Airport, flight path noise, affordable housing, simple functional design'},
{lat:37.4678,lng:126.9034,category:'villa',district:'금천구 가산동',caption:'Gasan digital valley area villa, 4-story amid tech parks, modern renovation, young professional tenants, convenience stores nearby'},
// ━━━ 아파트 (40) ━━━
{lat:37.5133,lng:127.1001,category:'apartment',district:'송파구 잠실동',caption:'Korean apartment complex, high-rise towers, numbered building signs in Korean, underground parking, landscaped common area, playground, Jamsil Seoul'},
{lat:37.3947,lng:127.1112,category:'apartment',district:'분당구 정자동',caption:'Bundang new city apartment, modern high-rise towers, well-maintained gardens, community facilities, wide pedestrian paths, Korean new town'},
{lat:37.5512,lng:127.0737,category:'apartment',district:'성동구 성수동',caption:'Korean apartment in urban area, mid-rise 15-story, renovated facade, parking structure visible, mature trees, mixed urban neighborhood'},
{lat:37.6313,lng:127.0477,category:'apartment',district:'노원구 하계동',caption:'Large Korean apartment complex, uniform 20-story towers in rows, communal green space, basketball court, 1990s mass housing'},
{lat:37.4844,lng:126.9017,category:'apartment',district:'금천구 가산동',caption:'Korean apartment towers near industrial area, 25-story buildings, parking ramp, convenience facilities at ground floor'},
{lat:37.4265,lng:127.0986,category:'apartment',district:'성남시 분당구',caption:'Premium Bundang apartment, 30-story luxury tower, glass curtain wall, underground parking, water feature entrance'},
{lat:37.5584,lng:126.8567,category:'apartment',district:'강서구 마곡동',caption:'Magok new development apartment, modern 35-story towers, eco-friendly design, rooftop solar, smart home features'},
{lat:37.3714,lng:127.1063,category:'apartment',district:'용인시 수지구',caption:'Suji Korean apartment, multiple 20-story buildings, hillside development, community park, school nearby, suburban apartment town'},
{lat:37.6534,lng:127.0612,category:'apartment',district:'노원구 상계동',caption:'Sanggye-dong mega complex, dozens of identical towers, numbered buildings, central playground, 1980s mass housing project'},
{lat:37.5034,lng:127.0489,category:'apartment',district:'강남구 대치동',caption:'Daechi-dong premium apartment, 25-story luxury towers, gated community, concierge entrance, luxury cars, prestigious Gangnam'},
{lat:37.5267,lng:127.1267,category:'apartment',district:'강동구 천호동',caption:'Cheonho-dong apartment, mixed 15-25 story towers, riverside location, Han River path access, renovated 2000s buildings'},
{lat:37.4923,lng:126.9834,category:'apartment',district:'서초구 반포동',caption:'Banpo apartment complex, premium high-rise, Han River view, luxury residential landmark, community sports facilities'},
{lat:37.5189,lng:126.8523,category:'apartment',district:'양천구 목동',caption:'Mokdong apartment, planned residential city, uniform mid-rise, wide tree-lined boulevards, excellent school district'},
{lat:37.6023,lng:126.9178,category:'apartment',district:'은평구 불광동',caption:'Bulgwang-dong apartment near mountain, 20-story towers with Bukhansan backdrop, hiking trail access, older complex renovating'},
{lat:37.5456,lng:126.9523,category:'apartment',district:'용산구 이촌동',caption:'Ichon-dong riverside apartment, classic Korean high-rise, Han River panoramic view, large communal garden, diplomatic neighborhood'},
{lat:37.5723,lng:127.0267,category:'apartment',district:'동대문구 답십리동',caption:'Dapsimni apartment, 15-story buildings, urban renewal project, new and old mixed, commercial street below, traditional market'},
{lat:37.4734,lng:126.8756,category:'apartment',district:'광명시',caption:'Gwangmyeong new town apartment, 40-story landmark towers, brand new, premium amenities, shopping mall, KTX station access'},
{lat:37.3912,lng:126.9567,category:'apartment',district:'안양시 동안구',caption:'Pyeongchon new town apartment, 1990s planned city, organized grid layout, community facilities, wide roads, Korean new town'},
{lat:37.6789,lng:126.7734,category:'apartment',district:'파주시 운정',caption:'Unjeong new town apartment, newest generation housing, 30+ story towers, smart city features, eco park, modern infrastructure'},
{lat:37.2912,lng:127.0534,category:'apartment',district:'수원시 영통구',caption:'Yeongtong new town apartment, Samsung city, modern 25-story towers, tech worker housing, clean organized, Gyeonggi science corridor'},
{lat:37.6345,lng:126.8912,category:'apartment',district:'고양시 일산서구',caption:'Ilsan new town apartment, 1st gen Korean new town, lake park nearby, 20-story buildings, established community, mature landscaping'},
{lat:37.5612,lng:126.8012,category:'apartment',district:'인천시 계양구',caption:'Gyeyang apartment, suburban Seoul satellite, 20-story towers, community sports center, school zone, affordable family housing'},
{lat:37.4134,lng:127.1289,category:'apartment',district:'성남시 중원구',caption:'Seongnam Junwon-gu apartment, older complex near city center, 15-story, traditional market below, urban renewal candidate'},
{lat:37.3589,lng:126.9345,category:'apartment',district:'군포시 산본',caption:'Sanbon new town apartment, 1990s planned housing, systematic layout, community park, library, Korean satellite city residential'},
{lat:37.5089,lng:127.0823,category:'apartment',district:'송파구 잠실동',caption:'Lotte Tower area apartment, ultra-premium high-rise, landmark neighborhood, luxury finishes, sky lounge, Seoul skyline views'},
{lat:37.4623,lng:126.9534,category:'apartment',district:'관악구 봉천동',caption:'Bongcheon redevelopment apartment, new 30-story tower replacing old villas, construction fence visible, transitioning neighborhood'},
{lat:37.6156,lng:127.0812,category:'apartment',district:'중랑구 망우동',caption:'Mangwoo-dong apartment, affordable housing, 15-story standard design, near cemetery park, quiet area, eastern Seoul suburb'},
{lat:37.5378,lng:126.8934,category:'apartment',district:'영등포구 여의도',caption:'Yeouido apartment, riverside luxury towers, political district, financial center, cherry blossom park, premium Seoul address'},
{lat:37.5834,lng:126.9089,category:'apartment',district:'서대문구 북아현동',caption:'Bugahyeon new town apartment, urban renewal, new 35-story towers replacing hillside villas, city center panoramic views'},
{lat:37.4512,lng:126.7034,category:'apartment',district:'인천시 남동구',caption:'Incheon Namdong apartment, large scale housing, near industrial zone, affordable suburban living, organized community'},
{lat:37.5167,lng:127.0167,category:'apartment',district:'강남구 도곡동',caption:'Dogok-dong apartment, education-focused premium area, tower apartments, academy street nearby, family luxury housing'},
{lat:37.4389,lng:127.1456,category:'apartment',district:'성남시 분당구 판교',caption:'Pangyo new town apartment, tech valley housing, modern architecture, green certification, young professional, smart city'},
{lat:37.5734,lng:126.8234,category:'apartment',district:'강서구 방화동',caption:'Banghwa apartment near airport, soundproofed design, 20-story, affordable housing zone, park and river access'},
{lat:37.6412,lng:126.6734,category:'apartment',district:'김포시 풍무동',caption:'Gimpo new town apartment, newest satellite city, 35-story modern towers, brand new infrastructure, GTX access planned'},
{lat:37.5623,lng:127.0812,category:'apartment',district:'광진구 구의동',caption:'Guui-dong apartment, riverside location, 25-story, Ttukseom park access, young demographic, trendy neighborhood'},
{lat:37.4856,lng:127.1012,category:'apartment',district:'송파구 위례',caption:'Wirye new town apartment, newest planned city, state-of-art design, underground utilities, parks integrated, premium suburban'},
{lat:37.3289,lng:126.8534,category:'apartment',district:'안산시 상록구',caption:'Ansan apartment, industrial city housing, 20-story standardized towers, multicultural neighborhood, affordable family housing'},
{lat:37.5489,lng:127.0489,category:'apartment',district:'성동구 왕십리',caption:'Wangsimni redevelopment apartment, urban transformation, brand new 30-story, commercial podium, subway direct connection'},
{lat:37.5067,lng:126.7456,category:'apartment',district:'인천시 서구 청라',caption:'Cheongna international city apartment, waterfront living, modern architecture, international school, expat-friendly'},
{lat:37.3167,lng:127.1067,category:'apartment',district:'용인시 기흥구',caption:'Giheung apartment, Samsung and SK semiconductor area, new construction, tech corridor housing, commuter-oriented design'},
// ━━━ 상가건물 (35) ━━━
{lat:37.5563,lng:126.9237,category:'commercial',district:'마포구 서교동',caption:'Korean commercial-residential in Hongdae, ground floor cafes with colorful signage, upper 3 floors residential, narrow street commercial'},
{lat:37.5667,lng:126.9784,category:'commercial',district:'종로구 관철동',caption:'Jongno commercial building, 5-story mixed-use, neon signs and Korean text banners, restaurants at every floor, busy commercial street'},
{lat:37.4979,lng:127.0276,category:'commercial',district:'서초구 서초동',caption:'Seocho commercial-residential, ground floor real estate office and pharmacy, residential above, clean modern facade, boulevard frontage'},
{lat:37.5408,lng:127.0696,category:'commercial',district:'성동구 성수동',caption:'Seongsu renovated commercial, former industrial converted to cafe and studio, exposed brick, large glass windows, hipster neighborhood'},
{lat:37.4844,lng:127.0326,category:'commercial',district:'서초구 방배동',caption:'Korean neighborhood commercial, 4-story, bakery and hair salon at ground floor, Korean signage, residential above, tree-lined street'},
{lat:37.5574,lng:126.9368,category:'commercial',district:'마포구 상수동',caption:'Sangsu-dong mixed-use, boutique shops and cafes at street level, 3 residential floors above, renovated vintage exterior'},
{lat:37.5722,lng:126.9851,category:'commercial',district:'종로구 익선동',caption:'Traditional Korean commercial, low-rise 2-3 story, hanok-style elements with modern renovation, small specialty shops, historic area'},
{lat:37.5102,lng:127.0592,category:'commercial',district:'강남구 삼성동',caption:'Gangnam commercial, 6-story modern office-retail, glass and stone facade, brand stores at ground floor, premium district'},
{lat:37.5156,lng:127.0189,category:'commercial',district:'강남구 역삼동',caption:'Gangnam business district commercial, ground floor bank and coffee chain, office floors above, glass curtain wall, corporate area'},
{lat:37.5489,lng:126.9912,category:'commercial',district:'중구 명동',caption:'Myeongdong commercial, cosmetics shops and restaurants, bright LED signage in Korean and English, tourist shopping district'},
{lat:37.5634,lng:126.9289,category:'commercial',district:'마포구 홍대입구',caption:'Hongdae entrance commercial, indie fashion shops, live music venue, graffiti-decorated exterior, young crowd, nightlife area'},
{lat:37.5023,lng:127.0034,category:'commercial',district:'서초구 교대역',caption:'Korean commercial near Gyodae station, 5-story, academy and tutoring centers, bookstore, residential above, education district'},
{lat:37.5178,lng:126.9089,category:'commercial',district:'영등포구 영등포동',caption:'Yeongdeungpo commercial, traditional market area, food stalls at ground floor, aging 4-story, Korean traditional market atmosphere'},
{lat:37.5789,lng:126.9667,category:'commercial',district:'용산구 이태원동',caption:'Itaewon commercial, international restaurants, bilingual signage, cosmopolitan atmosphere, leather goods shops, diverse styles'},
{lat:37.6212,lng:126.9134,category:'commercial',district:'은평구 구산동',caption:'Korean suburban commercial, ground floor supermarket and pharmacy, laundry shop, residential above, neighborhood commercial street'},
{lat:37.4867,lng:126.9289,category:'commercial',district:'관악구 신림역',caption:'Sillim station commercial, Korean BBQ and fried chicken restaurants, neon signs, 4-story mixed use, student-worker neighborhood'},
{lat:37.5445,lng:127.0545,category:'commercial',district:'성동구 왕십리역',caption:'Wangsimni station commercial, modern mixed-use, retail podium, residential tower above, Korean urban renewal commercial'},
{lat:37.6378,lng:127.0256,category:'commercial',district:'노원구 노원역',caption:'Nowon station commercial, station-front commercial, cram schools and restaurants, bright signage, pedestrian traffic'},
{lat:37.5312,lng:126.9623,category:'commercial',district:'용산구 녹사평역',caption:'Noksapyeong Korean commercial, gentrified area, craft beer bars, artisan shops, renovated old building, young professional neighborhood'},
{lat:37.5689,lng:127.0078,category:'commercial',district:'종로구 대학로',caption:'Daehangno commercial, small theater entrance, art gallery, bookstore cafe, cultural district commercial, student and artist area'},
{lat:37.5512,lng:127.0345,category:'commercial',district:'성동구 성수동',caption:'Seongsu container-style commercial, industrial chic renovation, cafe and workspace, young creative tenants, Instagram-famous spot'},
{lat:37.3812,lng:126.8012,category:'commercial',district:'안산시 중앙동',caption:'Ansan multicultural commercial street, Korean-Chinese-Vietnamese signage, diverse restaurants, 4-story mixed-use'},
{lat:37.4389,lng:127.1389,category:'commercial',district:'성남시 분당 서현동',caption:'Seohyeon commercial, new town center, franchise restaurants, academies, modern facade, planned commercial district'},
{lat:37.6534,lng:126.7756,category:'commercial',district:'파주시 금촌',caption:'Geumchon Korean small city commercial, local restaurants, hardware store, practical commercial strip, provincial town'},
{lat:37.2834,lng:127.0267,category:'commercial',district:'수원시 팔달문',caption:'Suwon traditional market area, historic fortress wall nearby, traditional food shops, aging commercial, cultural heritage zone'},
{lat:37.5545,lng:126.9723,category:'commercial',district:'중구 을지로',caption:'Euljiro commercial, traditional printing and metal workshops, retro atmosphere, hipster cafe openings, industrial heritage'},
{lat:37.5378,lng:126.9634,category:'commercial',district:'용산구 한남동',caption:'Hannam-dong upscale commercial, high-end restaurants, premium coffee shops, luxury retail, modern renovation, wealthy expat area'},
{lat:37.4712,lng:127.0489,category:'commercial',district:'서초구 양재역',caption:'Yangjae station commercial, flower market nearby, wholesale shops, restaurant row, Korean suburban commercial hub'},
{lat:37.5856,lng:127.0289,category:'commercial',district:'동대문구 회기역',caption:'Hoegi station commercial, university area, cheap restaurants, copy shops, bookstores, student-oriented Korean commercial street'},
{lat:37.5067,lng:126.9534,category:'commercial',district:'동작구 노량진',caption:'Noryangjin commercial, fish market area, seafood restaurants, study cafes for exam students, 24-hour activity'},
{lat:37.6156,lng:126.9989,category:'commercial',district:'강북구 미아역',caption:'Mia station commercial, neighborhood shopping, supermarket and clothing stores, Korean suburban commercial, family shopping area'},
{lat:37.5934,lng:127.0178,category:'commercial',district:'성북구 길음역',caption:'Gireum station commercial, new development mixed-use, franchise cafes, medical clinics, residential above, transit-oriented'},
{lat:37.4534,lng:126.8956,category:'commercial',district:'광명시 철산동',caption:'Cheolsan commercial, satellite city shopping street, diverse local shops, Korean suburban commercial district'},
{lat:37.5912,lng:127.0534,category:'commercial',district:'동대문구 장한평',caption:'Janganpyeong used car market area, auto parts shops, Korean industrial commercial, mechanical repair shops'},
{lat:37.5234,lng:127.0389,category:'commercial',district:'강남구 학동역',caption:'Hakdong station commercial, premium Korean commercial street, Italian restaurants, design studios, art galleries, upscale retail'},
// ━━━ 고급 단독주택 (25) ━━━
{lat:37.5923,lng:126.9712,category:'luxury',district:'종로구 평창동',caption:'Korean luxury detached house in Pyeongchang-dong, natural stone and wood facade, private garden with pine trees, iron gate, premium materials'},
{lat:37.5342,lng:127.0087,category:'luxury',district:'용산구 한남동',caption:'Hannam-dong luxury residence, modern minimalist, exposed concrete and glass, private courtyard, high walls, architectural design home'},
{lat:37.5678,lng:126.9543,category:'luxury',district:'서대문구 연희동',caption:'Yeonhui-dong upscale Korean house, 3-story detached, quality stone cladding, landscaped front yard, double garage, tree-lined street'},
{lat:37.4981,lng:127.0432,category:'luxury',district:'강남구 논현동',caption:'Modern Korean luxury villa in Gangnam, contemporary architecture, floor-to-ceiling windows, rooftop terrace, minimalist garden'},
{lat:37.5821,lng:126.9623,category:'luxury',district:'종로구 부암동',caption:'Buam-dong Korean luxury home, traditional aesthetic with modern comforts, stone wall boundary, mature garden, mountain backdrop'},
{lat:37.3891,lng:127.0923,category:'luxury',district:'성남시 분당구',caption:'Bundang luxury detached house, Western-Korean fusion design, large lot, professional landscaping, double-height living room visible'},
{lat:37.5912,lng:126.9789,category:'luxury',district:'종로구 삼청동',caption:'Samcheong-dong luxury hanok-modern fusion, traditional roof tiles with glass walls, private courtyard with bamboo garden'},
{lat:37.5289,lng:127.0012,category:'luxury',district:'용산구 이태원동',caption:'Itaewon luxury residence, international style, rooftop infinity pool, city skyline view, premium materials, exclusive neighborhood'},
{lat:37.5856,lng:126.9678,category:'luxury',district:'종로구 평창동',caption:'Pyeongchang-dong modern luxury, award-winning design, cantilever structure, Bukhansan view, infinity edge swimming pool'},
{lat:37.5167,lng:127.0034,category:'luxury',district:'강남구 청담동',caption:'Cheongdam-dong luxury townhouse, brand designer exterior, art in garden, wine cellar visible, chauffeur car, ultra-premium Seoul'},
{lat:37.5045,lng:127.0467,category:'luxury',district:'강남구 삼성동',caption:'Samsung-dong luxury detached, 3-story modern mansion, automated gate, CCTV, professional garden, Korean executive housing'},
{lat:37.5734,lng:126.9712,category:'luxury',district:'종로구 구기동',caption:'Gugi-dong luxury villa, nature-surrounded, traditional Korean pine garden, stone and wood materials, meditation space'},
{lat:37.5312,lng:127.0156,category:'luxury',district:'용산구 한남동',caption:'Hannam UN Village luxury, gated community, diplomatic quarter, international mansion, private security, embassy neighborhood'},
{lat:37.5623,lng:126.9412,category:'luxury',district:'서대문구 연희동',caption:'Yeonhui-dong architect house, unique angular design, full glass south facade, green roof, minimalist interior, residential art'},
{lat:37.4389,lng:127.1623,category:'luxury',district:'성남시 분당구',caption:'Bundang premium single house zone, 3-story with basement, European style exterior, manicured lawn, swimming pool, gated'},
{lat:37.3456,lng:127.1078,category:'luxury',district:'용인시 수지구',caption:'Suji luxury villa zone, Korean suburban mansion, large lot, mountain backdrop, outdoor BBQ, children playground, affluent suburb'},
{lat:37.6234,lng:126.9078,category:'luxury',district:'은평구 진관동',caption:'Eunpyeong Hanok Village luxury, modern hanok reinterpretation, traditional roof tiles, courtyard with lotus pond, cultural residential'},
{lat:37.4923,lng:127.0189,category:'luxury',district:'서초구 반포동',caption:'Banpo luxury single house, Han River proximity, 3-story contemporary, premium garden with outdoor kitchen, luxury SUV'},
{lat:37.5534,lng:126.9178,category:'luxury',district:'마포구 성산동',caption:'Seongsan-dong luxury duplex, modern Korean design, wood and glass facade, rooftop garden with city view, quiet Mapo pocket'},
{lat:37.6012,lng:126.9534,category:'luxury',district:'종로구 세검정',caption:'Segeomjeong valley luxury home, creek-side, traditional stone wall, modern interior behind traditional exterior, nature retreat'},
{lat:37.5467,lng:126.9645,category:'luxury',district:'용산구 후암동',caption:'Huam-dong hillside luxury, Namsan view, multi-level design following terrain, floor-to-ceiling windows, panoramic cityscape'},
{lat:37.5189,lng:127.0289,category:'luxury',district:'강남구 논현동',caption:'Nonhyeon luxury townhouse complex, uniform premium design, private parking, shared garden, quiet enclave in busy Gangnam'},
{lat:37.4678,lng:127.0834,category:'luxury',district:'송파구 방이동',caption:'Bangi-dong luxury single house, Olympic Park proximity, spacious lot, Korean modern design, private tennis court'},
{lat:37.5989,lng:126.9856,category:'luxury',district:'성북구 성북동',caption:'Seongbuk-dong luxury mansion, traditional elite neighborhood, large estate, classical Korean-Western fusion, old money Seoul'},
{lat:37.5378,lng:127.0089,category:'luxury',district:'용산구 한남동',caption:'Hannam luxury with art gallery, collector home, sculpture garden, architect-designed, cultural luxury lifestyle'},
// ━━━ 오피스텔 (15) ━━━
{lat:37.5033,lng:127.0498,category:'officetel',district:'강남구 역삼동',caption:'Korean officetel, 15-story narrow tower, glass curtain wall, small unit windows in grid, commercial ground floor, near subway, Gangnam business district'},
{lat:37.5563,lng:126.9723,category:'officetel',district:'중구 충무로',caption:'Korean urban officetel, 12-story mixed office-residential, modern facade, convenience store at ground, young professional housing near city center'},
{lat:37.4743,lng:126.8823,category:'officetel',district:'광명시',caption:'Suburban officetel near KTX station, 20-story modern tower, commercial podium, residential tower above, transit-oriented development'},
{lat:37.5134,lng:127.0589,category:'officetel',district:'강남구 삼성동',caption:'Premium Gangnam officetel, sleek modern, floor-to-ceiling windows, lobby with concierge, rooftop amenities, high-end urban living'},
{lat:37.5289,lng:126.8934,category:'officetel',district:'영등포구 여의도',caption:'Yeouido officetel tower, financial district, 25-story glass tower, business amenities, Han River view units, corporate worker housing'},
{lat:37.5623,lng:127.0456,category:'officetel',district:'광진구 건대입구',caption:'Konkuk University area officetel, student and worker housing, 18-story narrow tower, convenience shops, nightlife nearby'},
{lat:37.4856,lng:127.0178,category:'officetel',district:'서초구 서초동',caption:'Seocho station officetel, legal district, professional housing, modern 20-story, gym and study room, business casual neighborhood'},
{lat:37.5412,lng:126.9834,category:'officetel',district:'중구 서울역',caption:'Seoul Station area officetel, transportation hub, 22-story landmark, hotel-style amenities, mixed Korean and international tenants'},
{lat:37.5189,lng:127.0412,category:'officetel',district:'강남구 선릉역',caption:'Seolleung station officetel, IT startup corridor, co-working space, modern glass facade, 24-hour convenience, tech worker housing'},
{lat:37.4012,lng:127.1078,category:'officetel',district:'성남시 분당구',caption:'Bundang officetel complex, suburban business center, 15-story twin towers, clean modern, family-friendly amenities despite single units'},
{lat:37.5534,lng:126.9534,category:'officetel',district:'용산구 용산역',caption:'Yongsan station officetel, major development area, 30-story new construction, premium amenities, shopping complex connected'},
{lat:37.5789,lng:126.8923,category:'officetel',district:'마포구 DMC',caption:'DMC officetel, media broadcasting hub, modern tower, rooftop helipad, corporate tenant mix, Korean digital city development'},
{lat:37.5634,lng:127.0189,category:'officetel',district:'동대문구 DDP',caption:'DDP area officetel, design plaza nearby, fashion industry workers, 18-story modern tower, creative district housing'},
{lat:37.4534,lng:126.8512,category:'officetel',district:'부천시',caption:'Bucheon officetel, suburban affordable, 15-story standard, young single worker housing, near industrial zone, practical amenities'},
{lat:37.6289,lng:127.0189,category:'officetel',district:'노원구 노원역',caption:'Nowon officetel, northeastern Seoul suburban, affordable 12-story, student and worker housing, near university, budget urban living'},
// ━━━ 혼합용도 (15) ━━━
{lat:37.5447,lng:126.9512,category:'mixed',district:'용산구 이태원동',caption:'Itaewon mixed-use, 5-story, international restaurants and bars at ground, residential above, diverse architecture, cosmopolitan neighborhood'},
{lat:37.5562,lng:126.9366,category:'mixed',district:'마포구 상수동',caption:'Korean mixed-use, cafe and design studio at ground, creative office 2nd floor, residential loft above, renovated industrial, trendy Seoul'},
{lat:37.5103,lng:127.0652,category:'mixed',district:'강남구 삼성동',caption:'Gangnam mixed-use complex, retail podium with luxury brands, office floors glass facade, residential penthouse top, modern urban'},
{lat:37.5652,lng:126.9834,category:'mixed',district:'종로구 종로',caption:'Historic Jongno mixed-use, traditional commercial street, modern renovation preserving historic elements, shops and restaurants, residential above'},
{lat:37.5534,lng:127.0078,category:'mixed',district:'성동구 성수동',caption:'Seongsu mixed-use converted factory, ground floor artisan workshop, upper floor creative office and residential loft, industrial chic Korean'},
{lat:37.5167,lng:126.8712,category:'mixed',district:'양천구 목동',caption:'Mokdong mixed-use, academy and medical clinic lower, residential upper, suburban mixed-use, family neighborhood commercial-residential'},
{lat:37.5834,lng:126.9345,category:'mixed',district:'서대문구 신촌',caption:'Sinchon university area mixed-use, PC bang and study cafe at ground, cheap restaurants 2nd floor, gosiwon student housing above'},
{lat:37.5067,lng:127.0267,category:'mixed',district:'서초구 교대역',caption:'Gyodae mixed-use, law and accounting offices lower, premium residential upper, professional service building, institutional neighborhood'},
{lat:37.4623,lng:126.9412,category:'mixed',district:'관악구 서울대입구',caption:'SNU entrance mixed-use, student-oriented ground floor shops, study rooms and restaurants, dormitory-style housing above'},
{lat:37.6134,lng:127.0567,category:'mixed',district:'중랑구 면목동',caption:'Myeonmok-dong Korean mixed-use, traditional market ground floor, small workshop 2nd floor, residential above, local economy hub'},
{lat:37.5423,lng:126.9689,category:'mixed',district:'용산구 해방촌',caption:'Haebangchon mixed-use, gentrified hilltop, international cafe and gallery at ground, artist studio and residential above, multicultural'},
{lat:37.3734,lng:127.0867,category:'mixed',district:'용인시 수지구',caption:'Suji mixed-use, suburban new town, franchise restaurants below, premium apartment units above, planned suburban development'},
{lat:37.6378,lng:126.8745,category:'mixed',district:'고양시 일산동구',caption:'Ilsan mixed-use, entertainment and dining complex lower, officetel units above, lake park nearby, suburban weekend destination'},
{lat:37.5178,lng:126.9089,category:'mixed',district:'영등포구 문래동',caption:'Mullae-dong creative mixed-use, ironworks workshop ground floor, artist studio 2nd floor, residential above, industrial-creative hybrid'},
{lat:37.4867,lng:127.0667,category:'mixed',district:'송파구 석촌동',caption:'Seokchon mixed-use near Lotte Tower, boutique retail ground, professional offices middle, luxury residential top, premium Songpa'},
]

// 추가 5개 → 총 200
export const EXTRA_POINTS: TrainingPoint[] = [
{lat:37.5456,lng:126.9178,category:'villa',district:'마포구 대흥동',caption:'Daeheung-dong Korean villa, 4-story residential near university, student housing area, colorful murals on wall, narrow commercial alley'},
{lat:37.4789,lng:127.0612,category:'apartment',district:'강남구 개포동',caption:'Gaepo-dong Korean apartment redevelopment, old 10-story complex being demolished, new 35-story towers rising, construction cranes, transitioning neighborhood'},
{lat:37.5623,lng:126.9534,category:'commercial',district:'용산구 경리단길',caption:'Gyeongnidan-gil Korean commercial, trendy restaurants and bars, renovated old buildings, international food, young professional nightlife area'},
{lat:37.5845,lng:126.9834,category:'luxury',district:'종로구 가회동',caption:'Gahoe-dong luxury traditional hanok, fully restored with modern amenities, stone wall courtyard, traditional Korean roof tiles, Bukchon Hanok Village'},
{lat:37.5289,lng:127.0534,category:'officetel',district:'강남구 대치동',caption:'Daechi-dong officetel, education district, 16-story tower, academy workers and students, study-focused amenities, Korean cram school neighborhood'},
]
